### ISSUE TITLE
Error on windows 11

### ISSUE THREAD

**Issue by manuelvalera** [SmurphOfChaos/Warhammer-40-000-Average-Calculator#1]
Hello, I am working on a 3.10 python environment, and I get the following error after the program asks if I want to skip the intro:

 $ python Warhammer\ Python\ Code\ 1.1.py

Here is the Warhammer 40k Average Calculator, brought to you by the SMURPH_OF_CHAOS

How fast would you like the type to be; fast(f), medium(m), or slow(s)? (Currently the speed is set to medium)
f
Would you like to skip the intro?(y or n)n
Your options will appear below:
Traceback (most recent call last):
  File "C:\Users\dap21\Downloads\Warhammer-40-000-Average-Calculator-main\Warhammer-40-000-Average-Calculator-main\Warhammer Python Code 1.1.py", line 491, in <module>
    start()
  File "C:\Users\dap21\Downloads\Warhammer-40-000-Average-Calculator-main\Warhammer-40-000-Average-Calculator-main\Warhammer Python Code 1.1.py", line 428, in start
    sleep(typingSpeed)
TypeError: 'function' object cannot be interpreted as an integer
(paper)

I would like to see a requirements.txt file for this project, 

Thanks,

**Comment by SmurphOfChaos** [comment]
I don't understand why it is not working for you. I will do my best to fix it for you.

**Comment by SmurphOfChaos** [comment]
> i have realised the issue, thank you for pointing it out, should work now
